########################################################################
# Copyright (c) 2016 Rogue Wave Software Inc. and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#   Rogue Wave Software Inc. - initial implementation
########################################################################

language: java

jdk: oraclejdk8

cache:
  directories:
  - $HOME/.m2
  - $HOME/.composer/cache

before_install:	
  - sudo apt-get -qq update
  - sudo apt-get install curl php7-cli git
  - curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer
